Update noname

diff --git a/noname b/noname
--- a/noname
+++ b/noname
@@ -1,9 +1,134 @@
+View_User_info(){
+	ip=$(cat ${config_user_api_file}|grep "SERVER_PUB_ADDR = "|awk -F "[']" '{print $2}')
+	[[ -z "${ip}" ]] && Get_IP
+	ss_ssr_determine
+	clear && echo " Deatil Account ShadowsocksR"
+	echo -e "===================================================" && echo
+	echo -e " User [${user_name}] configuration info：" && echo
+	echo -e " IP : ${Green_font_prefix}${ip}${Font_color_suffix}"
+	echo -e " Port : ${Green_font_prefix}${port}${Font_color_suffix}"
+	echo -e " Password : ${Green_font_prefix}${password}${Font_color_suffix}"
+	echo -e " Encryption : ${Green_font_prefix}${method}${Font_color_suffix}"
+	echo -e " Protocol : ${Red_font_prefix}${protocol}${Font_color_suffix}"
+	echo -e " obfs : ${Red_font_prefix}${obfs}${Font_color_suffix}"
+    echo -e " Masa Aktif : ${Red_font_prefix}${exp}${Font_color_suffix}"
+	echo -e " Device limit : ${Green_font_prefix}${protocol_param}${Font_color_suffix}"
+	echo -e " Single thread speed limit : ${Green_font_prefix}${speed_limit_per_con} KB/S${Font_color_suffix}"
+	echo -e " Total user speed limit : ${Green_font_prefix}${speed_limit_per_user} KB/S${Font_color_suffix}"
+	echo -e " Forbidden port : ${Green_font_prefix}${forbidden_port} ${Font_color_suffix}"
+	echo
+	echo -e " Used traffic : Upload: ${Green_font_prefix}${u}${Font_color_suffix} + Download: ${Green_font_prefix}${d}${Font_color_suffix} = ${Green_font_prefix}${transfer_enable_Used_2}${Font_color_suffix}"
+	echo -e " Remaining traffic : ${Green_font_prefix}${transfer_enable_Used} ${Font_color_suffix}"
+	echo -e " Total user traffic : ${Green_font_prefix}${transfer_enable} ${Font_color_suffix}"
+	echo -e "${ssr_link}"
+ 	echo "==================================================="
+}
+
+# 设置 配置信息
+
+Set_config_user(){
+clear
 echo "Please enter the username you want to set (do not repeat, does not support Chinese, will be reported incorrect!)"
-read -e -p "(Default: adminssh):" ssr_user
-echo -e "Please enter the user port to be set"
-read -e -p "(Default: 2333):" ssr_port
-[[ -z "$ssr_port" ]] && ssr_port="2333"
-expr ${ssr_port} + 1 &>/dev/null
-echo "Please enter the user password you want to set"
-read -e -p "(Default: mfauzan58):" ssr_password
-[[ -z "${ssr_password}" ]] && ssr_password="mfauzan58"
+read -e -p "(Default: ):" ssr_user
+echo && echo ${Separator_1} && echo -e "	username : ${Green_font_prefix}${ssr_user}${Font_color_suffix}" && echo ${Separator_1} && echo
+read -p "Expired (hari): " masaaktif
+exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
+}
+Set_config_port(){
+lastport=$(cat /usr/local/shadowsocksr/mudb.json | grep '"port": ' | tail -n1 | awk '{print $2}' | cut -d "," -f 1 | cut -d ":" -f 1 )
+ssr_port=$((lastport+1))
+}
+Set_config_password(){
+ssr_password="$ssr_user"
+}
+Set_config_method(){
+ssr_method="aes-256-cfb"
+}
+Set_config_protocol(){
+ssr_protocol="origin"
+}
+Set_config_obfs(){
+ssr_obfs="tls1.2_ticket_auth_compatible"
+}
+Set_config_protocol_param(){
+ssr_protocol_param="2"
+}
+Set_config_speed_limit_per_con(){
+ssr_speed_limit_per_con=0
+}
+Set_config_speed_limit_per_user(){
+ssr_speed_limit_per_user=0
+}
+Set_config_transfer(){
+ssr_transfer="838868"
+}
+Set_config_forbid(){
+ssr_forbid=""
+}
+Set_config_enable(){
+	user_total=$(expr ${user_total} - 1)
+	for((integer = 0; integer <= ${user_total}; integer++))
+	do
+		echo -e "integer=${integer}"
+		port_jq=$(${jq_file} ".[${integer}].port" "${config_user_mudb_file}")
+		echo -e "port_jq=${port_jq}"
+		if [[ "${ssr_port}" == "${port_jq}" ]]; then
+			enable=$(${jq_file} ".[${integer}].enable" "${config_user_mudb_file}")
+			echo -e "enable=${enable}"
+			[[ "${enable}" == "null" ]] && echo -e "${Error} Get the current port[${ssr_port}]的禁用状态失败 !" && exit 1
+			ssr_port_num=$(cat "${config_user_mudb_file}"|grep -n '"port": '${ssr_port}','|awk -F ":" '{print $1}')
+			echo -e "ssr_port_num=${ssr_port_num}"
+			[[ "${ssr_port_num}" == "null" ]] && echo -e "${Error} 获取当前Port[${ssr_port}]的行数失败 !" && exit 1
+			ssr_enable_num=$(expr ${ssr_port_num} - 5)
+			echo -e "ssr_enable_num=${ssr_enable_num}"
+			break
+		fi
+	done
+	if [[ "${enable}" == "1" ]]; then
+		echo -e "Port [${ssr_port}] The account status is：${Green_font_prefix}Enabled ${Font_color_suffix} , switch to ${Red_font_prefix}Disabled${Font_color_suffix} ?[Y/n]"
+		read -e -p "(Default: Y):" ssr_enable_yn
+		[[ -z "${ssr_enable_yn}" ]] && ssr_enable_yn="y"
+		if [[ "${ssr_enable_yn}" == [Yy] ]]; then
+			ssr_enable="0"
+		else
+			echo "Cancel..." && exit 0
+		fi
+	elif [[ "${enable}" == "0" ]]; then
+		echo -e "Port [${ssr_port}] The account status is：${Green_font_prefix}Disabled ${Font_color_suffix} , switch to ${Red_font_prefix}Disabled${Font_color_suffix} ?[Y/n]"
+		read -e -p "(Default: Y):" ssr_enable_yn
+		[[ -z "${ssr_enable_yn}" ]] && ssr_enable_yn = "y"
+		if [[ "${ssr_enable_yn}" == [Yy] ]]; then
+			ssr_enable="1"
+		else
+			echo "取消..." && exit 0
+		fi
+	else
+		echo -e "${Error} 当前Port的禁用状态异常[${enable}] !" && exit 1
+	fi
+}
+
+View_User_info(){
+	ip=$(cat ${config_user_api_file}|grep "SERVER_PUB_ADDR = "|awk -F "[']" '{print $2}')
+	[[ -z "${ip}" ]] && Get_IP
+	ss_ssr_determine
+	clear && echo " Deatil Account ShadowsocksR"
+	echo -e "===================================================" && echo
+	echo -e " User [${user_name}] configuration info：" && echo
+	echo -e " IP : ${Green_font_prefix}${ip}${Font_color_suffix}"
+	echo -e " Port : ${Green_font_prefix}${port}${Font_color_suffix}"
+	echo -e " Password : ${Green_font_prefix}${password}${Font_color_suffix}"
+	echo -e " Encryption : ${Green_font_prefix}${method}${Font_color_suffix}"
+	echo -e " Protocol : ${Red_font_prefix}${protocol}${Font_color_suffix}"
+	echo -e " obfs : ${Red_font_prefix}${obfs}${Font_color_suffix}"
+  echo -e " Masa Aktif : ${Red_font_prefix}${exp}${Font_color_suffix}"
+	echo -e " Device limit : ${Green_font_prefix}${protocol_param}${Font_color_suffix}"
+	echo -e " Single thread speed limit : ${Green_font_prefix}${speed_limit_per_con} KB/S${Font_color_suffix}"
+	echo -e " Total user speed limit : ${Green_font_prefix}${speed_limit_per_user} KB/S${Font_color_suffix}"
+	echo -e " Forbidden port : ${Green_font_prefix}${forbidden_port} ${Font_color_suffix}"
+	echo
+	echo -e " Used traffic : Upload: ${Green_font_prefix}${u}${Font_color_suffix} + Download: ${Green_font_prefix}${d}${Font_color_suffix} = ${Green_font_prefix}${transfer_enable_Used_2}${Font_color_suffix}"
+	echo -e " Remaining traffic : ${Green_font_prefix}${transfer_enable_Used} ${Font_color_suffix}"
+	echo -e " Total user traffic : ${Green_font_prefix}${transfer_enable} ${Font_color_suffix}"
+	echo -e "${ssr_link}"
+ 	echo "==================================================="
+}
